name: Flyway Database Migration

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select database environment"
        required: true
        type: choice
        options:
          - beta
          - prod

jobs:
  migrate:
    runs-on: ubuntu-latest

    environment: ${{ inputs.environment }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Flyway migration
        uses: flyway/flyway-github-action@v1
        with:
          url: ${{ secrets.FLYWAY_URL }}
          user: ${{ secrets.FLYWAY_USER }}
          password: ${{ secrets.FLYWAY_PASSWORD }}
          locations: filesystem:sql/migrations
          command: migrate